[tool.poetry]
name = "echidna"
version = "0.1.0"
description = ""
authors = ["Aman"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
